March challenge QOSF Mentorship Screening Tasks
qosf/monthly-challenges pull request #49
Opened 2022-03-02 22:23 UTC by MaldoAlberto

I share the March challenge

2022-03-02 22:32 UTC, amirebrahimi requested changes
LGTM, just one small whitespace change

2022-03-02 22:32 UTC, amirebrahimi commented on README.md
> +[January 2022 Challenge](challenge-2022.01-jan/challenge-2022.01-jan.ipynb): Decompose
```suggestion
[January 2022 Challenge](challenge-2022.01-jan/challenge-2022.01-jan.ipynb): Decompose  
```

2022-03-03 03:20 UTC, MaldoAlberto commented on README.md
> +[January 2022 Challenge](challenge-2022.01-jan/challenge-2022.01-jan.ipynb): Decompose
Thanks  a lot @amirebrahimi  :raised_hands:

2022-03-03 17:06 UTC, amirebrahimi approved these changes

2022-03-11 09:21 UTC, merged